[project]
name = "reutils"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "torch>=2.6.0",
    "torchvision>=0.21.0",
]

[tool.uv.sources]
torch = { index = "pytorch-cu124" }
torchvision = { index = "pytorch-cu124" }
resselt = { index = "rewaifu" }

[[tool.uv.index]]
name = "pytorch-cu124"
url = "https://download.pytorch.org/whl/cu124"
explicit = true

[[tool.uv.index]]
name = "rewaifu"
url = "https://pypi.shd.llc/rewaifu/stable"
publish-url = "https://pypi.shd.llc/rewaifu/stable"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "resselt>=2,<3",
    "pepeline>=0.3.14",
    "typer>=0.15.2",
    "ruff>=0.11.0",
    "pre-commit>=4.1.0",
]
