[project]
name = "pepetorch"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "torch>=2.6.0",
    "torchvision>=0.21.0",
]

[tool.uv.sources]
torch = { index = "pytorch-cu124" }
torchvision = { index = "pytorch-cu124" }

[[tool.uv.index]]
name = "pytorch-cu124"
url = "https://download.pytorch.org/whl/cu124"
explicit = true

[[tool.uv.index]]
name = "yor"
url = "https://pypi.yor.ovh/simple/"
publish-url = "https://pypi.yor.ovh/"

[project.scripts]
pepetorch = "pepetorch:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
